# Generated by Django 3.2.9 on 2021-11-04 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Beer',
        ),
    ]
